# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    base_upload_dir: '%kernel.project_dir%/public/uploads'
    avatars_directory: '%base_upload_dir%/img/avatar'
    picture_directory: '%base_upload_dir%/img/tricks'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
#            $baseUploadDir: '%base_upload_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\Uploader:
        bind:
            $baseUploadDir: '%base_upload_dir%'

    App\Listener\PictureListener:
        tags:

            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Picture', method: 'prePersist'}
            - { name: 'doctrine.orm.entity_listener', event: 'preRemove', entity: 'App\Entity\Picture', method: 'preRemove'}
    App\Listener\TrickListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'preFlush', entity: 'App\Entity\Trick', method: 'preFlush'}
            - { name: 'doctrine.orm.entity_listener', event: 'postLoad', entity: 'App\Entity\Trick', method: 'postLoad'}

